macports/macports-legacy-support

include/MacportsLegacySupport.h
include/cmath
include/stdio.h
include/string.h
include/sys/fcntl.h
include/sys/mman.h
include/time.h
include/wchar.h

suppresses dozens of warning messages for C++ style comments
not being appropriate for older C standards

legacy-support: change comment style

---

include/time.h
src/time.c

`clockid_t` is the actual type of the first argument to both `clock_*` functions; it might be used by the calling code; just typedef it to be an `int` for easy compatibility. This change works for me to fix building `bladeRF` on OSX 10.5 PPC, which definitely does -not- have the `clock_*` functions.

time: add 'clockid_t'

---

include/MacportsLegacySupport.h
src/macports_legacy_realpath.c
src/macports_legacy_sysconf.c

tested on OSX10.6 and macOS 10.14. No warnings on either.

fix various compilation warnings

---

include/MacportsLegacySupport.h
include/MacportsLegacyWrappers/sysconf_support.h
include/MacportsLegacyWrappers/wrapper_macros.h
include/stdlib.h
include/unistd.h
src/macports_legacy_sysconf.c
test/test_realpath.c
test/test_sysconf.c

The idea is taken from Apple's own declaration of `realpath`: It boils down to
extern char *realpath(const char * __restrict, char * __restrict)
asm("_linker_symbol_for_realpath");
This means that we do not need to use macros for renaming symbols (except for temporarily moving the original declaration out of the way). The compiler does that for us where necessary (and only there). This preserves source-level API compatibility.
Take a look at `test/test_{realpath,sysconf}.c` for the scenarios tested. Some of those are close to existing practice, as `libuv` shows.
This pull request
* Uses opt-out (`__DISABLE_...` macros) again (in contrast to the [ccorn:globaldefs](https://github.com/ccorn/macports-legacy-support/tree/globaldefs) branch). As that approach is good enough for Apple's system …

Use asm symbol declarations for wrappers

---

README.md
include/MacportsLegacySupport.h
include/pthread.h
include/pthread_impl.h
test/test_pthread_rwlock_basic.c

this is a commonly used macro missing from Tiger
tested using the basic test here, and also using
the more detailed test from
Richard Stevens' Unix Network Programming Vol 2 Second Ed
Source here: https://www.kohala.com/start/unpv22e/unpv22e.html
in my_rwlock/test1.c

Tiger: add PTHREAD_RWLOCK_INITIALIZER

---

.gitignore
Makefile
README.md
include/MacportsLegacySupport.h
include/cmath
include/math.h
test/.gitignore
test/test_cmath.cc

Fix c++11 <cmath> PPC 10.[45], GNU g++ 4.6 through 6 only, by adding the following line of code -before- any of the GNU header are included:
`#define _GLIBCXX_USE_C99_MATH_TR1`
Also: <math.h> is for C declarations, while <cmath> is for C++ declarations, so put the correct declarations in the correct header. <cmath> includes <math.h>, so this change should not effect current ports that rely on this legacy header.
Add modeline to <cmath>; probably some whitespace fixes too.

Fix c++11 <cmath> PPC 10.[45], GNU g++ 4.6 through 6 only

---

include/math.h

* correctly pass through to the next math.h when not required for legacy support;
* also fixup the macros to work like those in <cmath> herein.

fixup! math.h

---

README.md
include/sys/stat.h
src/atcalls.c
test/test_fstatat64.c

This function is considered heavily private, but was added as a syscall anyway.
It's not actually exposed in system header files, but applications could call it via `syscall()`.
I do not expect a lot of applications to make use of it.
This PR depends upon #20.

Add `fstatat64` function.

---

Makefile
README.md
include/dirent.h
src/best_fchdir.c
src/fdopendir.c

This PR included support for building multiple variations of specific symbols.
Currently, it only does that for `fdopendir`. One consumer of this are newer versions of `go`, but you already know that.
We will probably need to eventually do this for other `atcalls` as well, but I'm too lazy to check which ones are necessary and refactor (split out) the code to do that. The good part is that this operation should be pretty easy to do, since this PR lays a solid foundation for this sort of things.
Also, documentation is added for this new feature (plus a bit of more general documentation that was missing).
Once this is merged, I will update the `legacy-support-devel` port to the new build procedure.

Create fdopendir variations (including ground work for multiple variations support)

---

tiger_only/bin/which

allows for constructs like
$ which tool || which toolalternative

which: exit 1 when the file is not found

---

README.md
include/MacportsLegacySupport.h
include/sys/fsgetpath.h
src/fsgetpath.c

needed for systems prior to 10.13
two methods of implementing fsgetpath are  available
we'll use the simpler syscall method for now
other method is included in source, protected by blocker
not simple to write a test for this at present

fsgetpath: implement replacement for 10.6+

---

include/sys/unistd.h
src/atcalls.c

Triggered by discussion at 
https://github.com/macports/macports-ports/commit/78b2cb450f7f56f0d1e6f66c44cd6e3a3fd742b1
Scanning through the API for `getatrlistat` in various OSX versions it turns out the API is slightly different to what we have here. Basically one argument is `void*` and not a specific type.  e.g. from macOS (10.15)
```
int     getattrlistat(int, const char *, void *, void *, size_t, unsigned long) __OSX_AVAILABLE_STARTING(__MAC_10_10, __IPHONE_8_0);
```
This MR just updates the API to match.
@kencu FYI

getattrlistat - Use void* instead of struct attrlist*

---

README.md
include/MacportsLegacySupport.h
include/strings.h
src/strings.c
test/test_ffsl.c

@kencu FYI. Stumbled over these via the new `Alembic` port
https://build.macports.org/builders/ports-10.6_x86_64-builder/builds/27179/steps/install-port/logs/stdio
Availability is
```
Oberon /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include > grep ffs strings.h
int	 ffs(int);
int	 ffsl(long) __OSX_AVAILABLE_STARTING(__MAC_10_5, __IPHONE_2_0);
int	 ffsll(long long) __OSX_AVAILABLE_STARTING(__MAC_10_9, __IPHONE_7_0);
```

Add implementations for ffsl (<10.5) and ffsll (<10.9)

---

src/fdopendir.c

`fdopendir` is supposed to take control of its `dirfd` parameter upon success.
An unrelated edge case in error handling was also fixed to not leak memory and a fd.
See https://github.com/evanw/esbuild/issues/348 for context.

fix fd leaks in fdopendir

---

README.md
include/MacportsLegacySupport.h
include/sys/aio.h

adds an include and several defs that were added
to this file in Leopard and beyond that current
software expects to find (eg mpich).

fix <sys/aio.h> for Tiger

---

include/MacportsLegacySupport.h
include/MacportsLegacyWrappers/wrapper_macros.h

This just fixes noisy build warnings, no change in behavior intended.
I could have just defined the macros to 0 if undefined instead in `include/MacportsLegacySupport.h`, but that way is probably more generic.

include: support undefined wrapping macros.

---

include/MacportsLegacySupport.h
src/atcalls.c
src/best_fchdir.c
src/common-priv.h
src/fdopendir.c

Less code duplication.
This header file lives in `src/` because it's not meant to be installed. It's fully private.
While that may not sound like a big deal yet, we'll use this more extensively soon. Trust me, it's a good thing.
As an added benefit, we can also consolidate `__pthread_fchdir()` and `best_fchdir`, which were exactly the same. Yay.

src: split out shared functionality to common-priv.h.

---

README.md
tiger_only/include/sys/types.h

A number of ports run into trouble compiling on Tiger because `_XOPEN_SOURCE` results in `_POSIX_C_SOURCE` being defined, thus hiding the `u_char`, `u_int`, and other typedefs.
Leopard and later provide a workaround in the form of `_DARWIN_C_SOURCE`; follow this behavior.
See: https://trac.macports.org/ticket/52070
See: https://trac.macports.org/ticket/62997
(Note that this PR will do nothing in practical terms until the `legacysupport` Portfile is modified.)

Define `u_char` etc on Tiger using Leopard rules

---

src/time.c

On versions of osx before 10.12, mach_timebase_info is a direct syscall (see dyld-239.3/glue.c#L434) which is order of magnitudes slower than the subsequent mach_absolute_time() call. Hence it's better to just cache it after the first call.
Since 10.12+, Apple also realized this and began caching mach_timebase_info calls at the libc layer (https://opensource.apple.com/source/xnu/xnu-3789.41.3/libsyscall/wrappers/mach_timebase_info.c.auto.html)

clock_gettime: Cache timebase

---

Makefile
README.md
include/dirent.h
src/best_fchdir.c
src/fdopendir.c
test/test_fdopendir.c
test/test_fmemopen.c
test/test_traverse.c
test/test_traverse_cwd.c

This pull request changes `fdopendir()` so that the supplied directory file descriptor remains open until `closedir()` is called. This makes it possible for functions like `fstatat()` and `unlinkat()` to use the directory file descriptor (without changing its state) while traversing a directory hierarchy.
This was prompted by a pull request to get the sysutils/rawhide port working with legacysupport:
https://github.com/macports/macports-ports/pull/19047
https://trac.macports.org/ticket/67754
It changes `include/dirent.h` to include a wrapper struct and macro for `DIR` that contains the real `DIR*` as well as an `int` to store the supplied directory file descriptor. All of the functions that take a `DIR*` as an argument need wrappers as well.
There are wrapper macros for `readdir()`, …

Fix fdopendir so dirfd stays open until closedir (for fstatat etc)

---

test/test_fstatat64.c

On newer macOS releases - like, say, 10.15 - the test for `fstatat64` fails to build:
```
test/test_fstatat64.c:93:12:
error: implicit declaration of function 'fstatat64' is invalid in C99
if (0 != fstatat64 (AT_FDCWD, argv[0], &atfdcwd_stat64, 0)) {
^
```
Since this syscall is provided via header `sys/sysproto.h` - within `Kernel.framework` - it's not ideal to depend on the latter. So rather than going down that path, simply add a local declaration for `fstatat64`.
Fixes: [Ticket 65913 - legacy-support: tests: failure due to fstatat64](https://trac.macports.org/ticket/65913)

fstatat64: tests: add declaration for fstatat64 syscall, to fix build issues for newer macOS releases

---

include/time.h
src/time.c
test/test_time.cpp

This seems the best source of that value on macOS since 10.0

Implement `CLOCK_THREAD_CPUTIME_ID` via `thread_info`

---

Makefile
src/atcalls.c
test/do_test_faccessat_setuid
test/test_faccessat.c
test/test_time.cpp

This pull request comes from https://github.com/macports/macports-legacy-support/pull/65.
@acjones8 realised that `faccessat` didn't work with `AT_EACCESS`. It just returns -1 with errno set to `EINVAL`. That prevents emacs from installing on old systems. They suggested silently ignoring `AT_EACCESS`.
@catap contributed an approximate implementation to actually implement `AT_EACCESS` instead.
I wrote some tests for `faccessat` and fixed the new implementation.
I realised that the existing `faccessat` implementation didn't actually work at all in setuid/setgid programs where it really matters. It was always checking effective user access, not real user access, which is what `faccessat` is supposed to check by default. So it only works in non-setuid non-setgid programs where the real user …

Fix faccessat (setuid, setgid, AT_EACCESS, F_OK)

---

Makefile
README.md
include/dirent.h
src/fdopendir.c
test/do_test_faccessat_setuid
test/test_faccessat.c

Originally, fdopendir was declared in dirent.h
using __DARWIN_ALIAS_I. I think this was needed
because the original implementation had local
variables of type struct statbuf, and so its
translation unit needed to be compiled multiple
times, once for each inode size, and each version
would be differently labelled, and __DARWIN_ALIAS_I
was probably needed to select the correctly
labelled version of fdopendir. But I am guessing.
The current implementation no longer uses any
struct statbuf local variables, and so is only
compiled once. I think this means that it is no
longer necessary to use __DARWIN_ALIAS_I when
declaring fdopendir. Perhaps surprisingly, it
still worked with __DARWIN_ALIAS_I in place.
So maybe I'm guessing wrong.
However, the clang-devel port failed to compile
on macOS-10.9, …

Fix dirent.h clang-devel build failure on 10.9, and 10.4 build failure

---

Makefile

This reverts an earlier change to Makefile which led to needed `_fdopendir*` symbols being missing from the `legacy-support` dylib.
See https://github.com/macports/macports-ports/pull/22617#issuecomment-1937102831
@kencu @macportsraf @mascguy @cjones051073 @catap

Makefile: fix fdopendir

---

.gitignore
src/fdopendir.c
test/.gitignore
test/test_fdopendir.c

This was triggered by noticing that the fdopendir(stdin) test was failing (due to returning the wrong errno) when run from a pipe rather than a tty or pty.  This led to adding two more tests, which in turn led to finding additional bugs.  These bugs are fixed here, and the commit order is rearranged to put the fixes before the test additions, to avoid creating a pothole in the history.
There are also some additional cleanups, both related and unrelated, as separate commits.
See the individual commit messages for more information.
This has been tested on all non-oddball platforms except 13.x+ x86_64, as well as on 10.4 x86_64 (which tends to be a problem case).  Building and testing "bare" in this repo (non-universal only) successfully builds and passes tests on all such platforms. …

Fix some expected fdopendir() failures, plus some other cleanups

---

src/dirfuncs_compat.c
src/dirfuncs_compat.h
test/test_dirfuncs_compat.c
test/test_fdopendir.c

The __mpls_* wrappers are no longer needed for the new fdopendir() implementation, but many existing dependents may still have references to them.  This adds those functions back as transparent wrappers for the corresponding OS calls.
This also adds tests for the wrappers, by applying the existing tests (in test_fdopendir) to the wrappers via macro replacements.
TESTED:
Tested on 10.4-10.5 ppc, 10.5-10.6 ppc (x86_64 Rosetta), 10.4-10.6 i386, 10.4-12.x x86_64, and 11.x-14.x arm64.
Builds on all tested platforms except 10.5 ppc +universal, and passes all tests in all buildable cases, including the new tests. Comparison with "nm" shows that no global definitions were removed from the libraries since v1.1.1, with additions as needed for the new fdopendir(), and no differences at all for OS …

Add compatibility entries for obsolete __mpls_* funcs.

---

include/time.h
src/dirfuncs_compat.c

Also corrects typo in same comment.
Also corrects typo in unrelated comment in time.h.

dirfuncs_compat: Add comment regarding retention.

---

README.md
include/MacportsLegacySupport.h
include/sys/socket.h
test/test_cmsg_macro.c

This is two commits - one to fix the issue, and one to add the test.  See the individual commit messages for more details.

sys/socket.h: Fix CMSG_DATA definition in <10.6

---

include/MacportsLegacySupport.h
include/unistd.h

Apple's implementation of sysconf(_SC_PHYS_PAGES) never worked on i386.  It wasn't provided until 10.11, which requires x86_64, so the problem is never seen in ordinary native builds.  It is visible in i386 builds for 10.11+, including universal builds with i386.  Since MacPorts dropped i386 from the default universal_archs in 10.14, it's not normally seen in 10.14+.  It can be seen in the test failures in the 10.11-10.13 +universal cases.
The fix is simply to use the working legacy-support implementation in all i386 builds, regardless of OS version.
TESTED:
Tested on 10.4-10.5 ppc, 10.5-10.6 ppc (x86_64 Rosetta), 10.4-10.6 i386, 10.4-12.x x86_64, and 11.x-14.x arm64.
Builds on all tested platforms except 10.4 ppc +universal, and passes all tests in all buildable cases, including the …

sysconf(_SC_PHYS_PAGES): Always use wrapper on i386

---

include/MacportsLegacySupport.h

Minor fix for warning:
```
src/macports_legacy_sysconf.c:21:5: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
#if __MP_LEGACY_SUPPORT_SYSCONF_WRAP__
^
include/MacportsLegacySupport.h:126:65: note: expanded from macro '__MP_LEGACY_SUPPORT_SYSCONF_WRAP__'
|| defined(__i386)))
^
```
See: https://github.com/macports/macports-legacy-support/pull/75#discussion_r1531006443
CC: @fhgwright

__MP_LEGACY_SUPPORT_SYSCONF_WRAP__: fix nested macro expansion warning

---

include/MacportsLegacySupport.h

Minor fix necessary, due to an oversight by Yours Truly. Resolves build failures for 32-bit/i386.
See: https://github.com/macports/macports-legacy-support/pull/75
See: https://github.com/macports/macports-legacy-support/pull/77
CC: @fhgwright

__MP_LEGACY_SUPPORT_I386__: define unconditionally, as a one/zero boolean

---

test/test_dirfuncs_compat.c

Since dirfd() may be defined as a macro, it needs to be undefined before defining it, to avoid a warning.
TESTED:
Tested on 10.4-10.5 ppc, 10.4-10.6 i386, 10.5-10.6 ppc (i386 Rosetta), 10.5-12.x x86_64, 11.x-14.x arm64.
Redfinition warning is now gone.

test_dirfuncs_compat: Fix warning

---

include/string.h

This is one case of the general problem in:
https://trac.macports.org/ticket/69867
This should fix the only known case specifically related to collisions with "secure" wrappers.  Whether there are other types of SDK collisions is TBD.
TESTED:
Builds and passes tests on 10.4-10.5 ppc, 10.4-10.6 i386, 10.5-10.6 ppc (i386 Rosetta), 10.5-12.x x86_64, 11.x-14.x arm64. Builds test_stpncpy successfully on 10.6 with 10.7 SDK.

stpncpy: Fix potential header collision with "later" SDK

---

Makefile
include/string.h
src/stpncpy.c
src/stpncpy_chk.c
test/test_stpncpy_chk.c
test/test_stpncpy_chk_force1.c
test/test_stpncpy_chk_forced.c

See the two commit messages.
Tested on:
```
Mac OS X 10.4.11 8S165, PPC, Xcode 2.5 8M2558
Mac OS X 10.5.8 9L31a, PPC, Xcode 3.1.4 9M2809
Mac OS X 10.5.8 9L31a, PPC (i386 Rosetta), Xcode 3.1.4 9M2809
Mac OS X 10.6.8 10K549, PPC (i386 Rosetta), Xcode 3.2.6 10M2518
Mac OS X 10.7.5 11G63, x86_64, Xcode 4.6.3 4H1503
OS X 10.8.5 12F2560, x86_64, Xcode 5.1.1 5B1008
OS X 10.9.5 13F1911, x86_64, Xcode 6.2 6C131e
OS X 10.10.5 14F2511, x86_64, Xcode 7.2 7C68
OS X 10.11.6 15G22010, x86_64, Xcode 8.1 8B62
macOS 10.12.6 16G2136, x86_64, Xcode 9.2 9C40b
macOS …
```

Add implementation and tests for stpncpy() security wrapper

---

README.md
include/MacportsLegacySupport.h
include/sys/queue.h
test/test_fstatat64.c
test/test_queues.c

See the individual commit messages.

Add two new queue macros with tests, plus a warning fix.

---

README.md
include/MacportsLegacySupport.h
include/unistd.h
manual_tests/darwin_c.c
src/fgetattrlist.c
test/test_fgetattrlist.c
test/test_fsetattrlist.c

This adds an implementation of `fgetattrlist()`. Tested on 10.14.6, 10.6.8, and 10.4.11 (ppc) but only the 10.4 test means anything. The test is very basic. It just calls the function on the current directory's file descriptor, and only requires that it doesn't return an error.
I noticed a strange thing when testing on 10.4 (ppc). The first time I run:
PATH=/opt/local/bin:$PATH CC=gcc-apple-4.2 CFLAGS=-isystem`pwd`/tiger_only/include make test
I get an error:
ld: file not found: src/fdopendir.dl.o.inode32.ppc
But if I run it again, it works. This happens with or without this change. I suspect that it doesn't matter.

Add fgetattrlist()

---

Makefile
include/MacportsLegacySupport.h
src/realpath.c
test/test_realpath.c
test/test_realpath_compat.c
test/test_realpath_nonext.c
test/test_realpath_nonposix.c
tools/.gitignore
tools/realpath_test.c

See the individual commit messages.
Highlights:
- Rewrites realpath() wrapper to handle its variants more correctly.
- Expands realpath() tests to cover all variants.

Multiple updates, mostly for realpath()

---

Makefile
README.md
include/MacportsLegacySupport.h
src/add_symbols.c
src/realpath.c
test/test_realpath.c
test/test_realpath_compat.c

- Fix 10.6 non-POSIX realpath()
- Add test case demonstrating 10.6 non-POSIX bug.

Additional realpath() fixes

---

Makefile
include/MacportsLegacySupport.h
include/dirent.h
include/sys/cdefs.h
manual_tests/cdefsinfo.c
src/atcalls.c
src/atcalls.h
src/best_fchdir.c
src/common-priv.h
src/dirfuncs_compat.c
src/fdopendir.c
src/setattrlistat.c
src/statxx.c
test/test_dirfuncs_compat.c
test/test_stpncpy_chk.c
test/test_strncpy_chk.c
xtest/test_scandir.c

Notably:
- Adds support for code that can't tolerate the normal `scandir()` fix.
- Limits unavoidable GCC warnings to cases that really need the fix.
Tested (both from repo and from temp Portfile) on:
```
Mac OS X 10.4.11 8S165, PPC, Xcode 2.5 8M2558
Mac OS X 10.4.11 8S2167, x86_64, Xcode 2.5 8M2558
Mac OS X 10.5.8 9L31a, PPC, Xcode 3.1.4 9M2809
Mac OS X 10.5.8 9L31a, PPC (i386 Rosetta), Xcode 3.1.4 9M2809
Mac OS X 10.6.8 10K549, PPC (i386 Rosetta), Xcode 3.2.6 10M2518
Mac OS X 10.7.5 11G63, x86_64, Xcode 4.6.3 4H1503
OS X 10.8.5 12F2560, …
```

Multiple changes (primarily cleanups) - see individual commits

---

Makefile
include/AvailabilityMacros.h
include/MacportsLegacySupport.h
include/TargetConditionals.h
include/_macports_extras/tiger_only/copyfile.h
include/copyfile.h
include/sys/stat.h
src/.gitignore
src/Makefile
src/add_symbols.c
src/copyfile.3
src/copyfile.c
src/filesec_internal.h
src/quarantine.h
src/statxx.c
test/test_copyfile.c
test/test_stat.c
xtest/test_targetconds.c

Tested, both from repo and as a temporary Portfile, on:
```
Mac OS X 10.4.11 8S165, PPC, Xcode 2.5 8M2558
Mac OS X 10.4.11 8S2167, x86_64, Xcode 2.5 8M2558
Mac OS X 10.5.8 9L31a, PPC, Xcode 3.1.4 9M2809
Mac OS X 10.5.8 9L31a, PPC (i386 Rosetta), Xcode 3.1.4 9M2809
Mac OS X 10.6.8 10K549, PPC (i386 Rosetta), Xcode 3.2.6 10M2518
Mac OS X 10.7.5 11G63, x86_64, Xcode 4.6.3 4H1503
OS X 10.8.5 12F2560, x86_64, Xcode 5.1.1 5B1008
OS X 10.9.5 13F1911, x86_64, Xcode 6.2 6C131e
OS X 10.10.5 14F2511, x86_64, Xcode 7.2 7C68
OS X 10.11.6 15G22010, x86_64, …
```

Fixes for copyfile(), *statx() and TargetConditionals

---

README.md
include/mach/machine.h
xtest/test_cputypes.c

This is an additional change to fix https://trac.macports.org/ticket/71621, as well as previously neglected updates to README.md.
Tested new code (repo only) on
```
Mac OS X 10.4.11 8S165, PPC, Xcode 2.5 8M2558
Mac OS X 10.4.11 8S2167, x86_64, Xcode 2.5 8M2558
Mac OS X 10.5.8 9L31a, PPC (i386 Rosetta), Xcode 3.1.4 9M2809
Mac OS X 10.6.8 10K549, PPC (i386 Rosetta), Xcode 3.2.6 10M2518
Mac OS X 10.7.5 11G63, x86_64, Xcode 4.6.3 4H1503
OS X 10.8.5 12F2560, x86_64, Xcode 5.1.1 5B1008
OS X 10.9.5 13F1911, x86_64, Xcode 6.2 6C131e
OS X 10.10.5 …
```

Add CPU_TYPE_ARM; update README

---

Makefile
README.md
include/MacportsLegacySupport.h
src/sysctl.c
src/time.c
test/test_clocks.c
tools/boottime.c

Notably:
- Fixes boottime sysctls for 64-bit <10.6
- Consequently undisables sleep offset on ppc64
Tested on:
```
Mac OS X 10.4.11 8S165, ppc, Xcode 2.5 8M2558
Mac OS X 10.4.11 8S165, ppc64, Xcode 2.5 8M2558
Mac OS X 10.4.11 8S2167, x86_64, Xcode 2.5 8M2558
Mac OS X 10.4.11 8S2167, ppc (i386 Rosetta), Xcode 2.5 8M2558
Mac OS X 10.5.8 9L31a, ppc, Xcode 3.1.4 9M2809
Mac OS X 10.5.8 9L31a, ppc64, Xcode 3.1.4 9M2809
Mac OS X 10.5.8 9L31a, ppc (i386 Rosetta), Xcode 3.1.4 9M2809
Mac OS X 10.6.8 10K549, ppc (i386 Rosetta), Xcode 3.2.6 10M2518
Mac OS X …
```

Boottime fixes et al
